### ISSUE TITLE
Build error: Failed compiling object src/mime.obj

### ISSUE THREAD

**Issue by ThomasJanuary88** [lipp/lua-websockets#110]
I got Lua 5.3.4 and Luarocks installed

When I'm installing depedencies with this command
`D:\LUA_LOVE2D\webSocket\lua-websockets>luarocks make rockspecs/lua-websockets-scm-1.rockspec`

I got this result and then an error

> Missing dependencies for lua-websockets scm-1:
   luasocket (not installed)
   luabitop (not installed)
   lua-ev (not installed)
   copas (not installed)
   luasec (not installed)

> lua-websockets scm-1 depends on luasocket (not installed)
Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock
cl /nologo /MD /O2 -c -Fosrc/mime.obj -IC:/program files (x86)/lua/5.3/include src/mime.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DNDEBUG -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
'cl' is not recognized as an internal or external command,
operable program or batch file.

> Error: Failed installing dependency: https://luarocks.org/luasocket-3.0rc1-2.src.rock - Build error: Failed compiling object src/mime.obj

**Comment by ThomasJanuary88** [comment]
I find a solution here : http://www.thijsschreijer.nl/blog/?p=863

**Comment by hbasafa** [comment]
The link is no more available. Any other source?
