### ISSUE TITLE
Handshake fails on iOS/Android

### ISSUE THREAD

**Issue by ayyoitsp** [lipp/lua-websockets#17]
Handshake is failing due to mismatched auth.  It may be an endian issue.  Lost my output, but will attach some logs tomorrow.

**Comment by EnTerr** [comment]
Glad i found this issue, guys!
I am trying the echo example to ws://echo.websocket.org with sync client and failing with "Websocket Handshake failed: Invalid Sec-Websocket-Accept (expected AnDKkAsrkWcWifKgdqIeekL8lH0= got gnDKkIsrkWcWifKg9qIeesL8lH0=)"

I am on pure Lua 5.1, so trying to use
* struct = [lua-struct](https://github.com/iryont/lua-struct)
* bit = [lua-bit-numberlua](https://github.com/davidm/lua-bit-numberlua)

Thanks to the @lipp example ('The quick brown fox jumps over the lazy dog'), i was able to figure that i have to use numberlua in `LuaBitOp` compatiubility mode, i.e. `bit = require 'bit.numberlua'.bit` (and not in the default or `bit32` compatibility mode). I suspect that's what @BoarK meant by "to require it properly'. Now i'll follow down the `band` clue he dropped and see if that might be a reason for some mishap in `frame.decode()` ....

**Comment by EnTerr** [comment]
Update: turned out the issue was with the `struct` library doing some of the packing wrong. After fixing it websockets works like a charm! 

So if someone else runs in this problem... check your struct functionality

**Comment by lipp** [comment]
@EnTerr :+1: what kind of struct problem did you have?

**Comment by EnTerr** [comment]
In my particular case,  bytes were not getting packed/unpacked right
https://github.com/iryont/lua-struct/issues/2
