### ISSUE TITLE
handshake.http_headers won't read Sec-WebSocket-Accept line

### ISSUE THREAD

**Issue by BoarK** [lipp/lua-websockets#22]
I'm connecting to a simple echo server using websocket.io on localhost.  The Sec-WebSocket-Accept line sent from this websocket.io server does not end with a \r\n so the key check fails.

Change made to handshake.http_headers

  --for line in request:gmatch('[^\r\n]*\r\n') do
  for line in request:gmatch("[^\r\n]+") do

Tested on both echo.websocket.org and localhost.

**Comment by pritammore** [comment]
Hi @lipp 

I am getting the Handshake failed Error.
currently, lua-websockets is configured in openwrt OS and trying to connect Server done using Ratchet-Websockets.

Below error is received.
`Websocket Handshake failed: Invalid Sec-Websocket-Accept (expected N9CxZL/lcu6fXwp/V9XHv9kIX6w= got nil)`

Pritam
