### ISSUE TITLE
is there a example of client_ev?

### ISSUE THREAD

**Issue by yanpeipan** [lipp/lua-websockets#45]

**Comment by lipp** [comment]
will provide an echo-client-ev example soon.
you can read the tests for getting an idea until then:
https://github.com/lipp/lua-websockets/blob/master/spec/client_ev_spec.lua

**Comment by lipp** [comment]
here is an example (frankly, not tested yet - my lua env is temp broken...):

https://github.com/lipp/lua-websockets/blob/add-example/examples/echo-client-ev.lua
