### ISSUE TITLE
Request for functionality: get response with selected subprotocol

### ISSUE THREAD

**Issue by KSDaemon** [lipp/lua-websockets#59]
Hi! 
Another one problem: if websocket client send multiple ws subprotocols, then server can choose one, and answer with corresponding header. On client side we should have a possibility to know that answer. Cause application logic may rely on that.

**Comment by lipp** [comment]
agree. we can add a second return value to connect

```lua
local ok,protocol = ws:connect('ws://foo.bar', {'proto1','proto2'})
```

**Comment by moteus** [comment]
May be client/server also can get all headers from handshake?

**Comment by lipp** [comment]
ok, so you suggest:

```lua
local ok,headers = ws:connect(...)
```

or

```lua
local ok,protocol,headers = ws:connect(...)
```

i am ok with both options

**Comment by moteus** [comment]
I suggest `ok,protocol,headers`.
Also may be allows client/server add some headers manually. But I do not know for what it may be needed.

**Comment by lipp** [comment]
ok, great. 

regarding specifying header when connecting: i dont like to add functionality without somebody nedding it, though. every feature has to be tested and maintained, espacially if they are seldom or rather never used.

**Comment by KSDaemon** [comment]
Hi guys! I vote for local ok,protocol,headers = ws:connect(...)
That would be enough.

**Comment by KSDaemon** [comment]
Hi, guys! On this weekend i decided to implement this feature. But i was a bit confused: in client_ev we can not simply return headers, 'cause things are async. So i extended response form on_open function — now it returns websocket object, server selected protocol and all response headers. 
For sync client — all return points in connect function are extended appropriately.

**Comment by lipp** [comment]
there is a new PR #73
