### ISSUE TITLE
Is closing socket really needed?

### ISSUE THREAD

**Issue by SyRenity** [lipp/lua-websockets#69]
In the example I see that the socket is closed:
https://github.com/lipp/lua-websockets/blob/master/examples/echo-server-copas.lua

```lua
    if message then
      ws:send(message)
    else
      ws:close()
      return
    end
```

I tried both with and without, and it seems there is no need to re-open the socket from the client site.

What is the actual use of this, and is it really needed?

**Comment by lipp** [comment]
you can skip `close` as the server closes on error (https://github.com/lipp/lua-websockets/blob/master/src/websocket/sync.lua#L84).

i recommend to call close anyhow to be more verbose on resource management.

**Comment by SyRenity** [comment]
@lipp Just to confirm, it will go to the error branch if the message was not received during step timeout?

Or there are other conditions that it can end up on the error code branch?
