### ISSUE TITLE
help! - attempt to call upvalue 'rol' (a nil value)

### ISSUE THREAD

**Issue by rossbcan** [lipp/lua-websockets#78]
Hi;
I have chosen lua-websockets (and ported it and dependencies to OpenWrt packages) for the client portion of a licencing client / server, which may be extended for a remote configuration service.

Lua 5.1 (and, cannot upgrade without breaking a lot of Lua portion of OpenWrt, such as Luci

I am missing bit operations support (issue title, not shown in dependencies) and, seek advice regarding how to remedy this. An outline of alternatives is here: http://lua-users.org/wiki/BitwiseOperators

From which the best practice is suggested to use Lua BitOp (library, Lua API). Is this true, or, anyone have a better recommendation?

Also, I note that luacrypto (optionally) is an openssl wrapper. I have luasec for this ( http://luasec.luaforge.net/), which appears to be a more modern implementation. Any plans / advice regarding using luasec as opposed to luacrypto, or, is my best option to port luacrypto?

Full disclosure: relative Lua newbie, but intend to catch up (engineer)

Thanks for considering...

Bill Ross

**Comment by rossbcan** [comment]
temporary? workaround (echo-client-ev.lua works):

use luaJIT (as opposed to lua) which:
a) has required bit operations
b) is binary comparable with lua extensions such as lua-ev
c) is blazing fast compared to lua

still interested to answers to above questions and very interested in SSL (wss) support.

**Comment by lipp** [comment]
@rossbcan right now you need either lua 5.1 + luabitop or luajit or lua >= 5.2

client wss support is on list. server wss is unlikely.
