### ISSUE TITLE
Upload last version to luarocks?

### ISSUE THREAD

**Issue by endel** [lipp/lua-websockets#85]
Hi there!

It seems that the [last published version (v2.1-1)](http://luarocks.org/modules/lipp/lua-websockets) is outdated, as it uses `struct` dependency instead of the new bitops.

Is there a way to install the latest lua-websockets version using `luarocks`?
Thanks!

**Comment by lipp** [comment]
@endel i'll do a new release soon.

**Comment by ntd** [comment]
:+1:

**Comment by lipp** [comment]
sorry for being late. i'll try to do it today...

**Comment by lipp** [comment]
@endel @ntd done (v2.2) : https://luarocks.org/modules/lipp/lua-websockets

**Comment by ntd** [comment]
Thanks @lipp

**Comment by lipp** [comment]
@ntd you are welcome!
